### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by jompa68** [blakeblackshear/blakeshome-charts#19]
Trying to install this chart but what ever i try in config it never installs correct.

**Comment by onedr0p** [comment]
There could be many reasons for this not working for you, and we cannot help with a "doesn't work" message like you posted here. Kubernetes is very complex and it could be a many number of things not working that might not even related to this helm chart. Please do some debugging on your end and post logs, kubernetes describes etc.. of issues you are facing.
