### ISSUE TITLE
no matches for kind "Ingress" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by echel0n** [blakeblackshear/blakeshome-charts#20]
Using Kubernetes v1.22.2 and can't install frigate via helm, getting error "Helm install failed: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1""

**Comment by onedr0p** [comment]
A PR was opened but doesn't look like there was any activity on it after my review https://github.com/blakeblackshear/blakeshome-charts/pull/18

**Comment by echel0n** [comment]
Thanks for taking care of this!
