### ISSUE TITLE
Restream

### ISSUE THREAD

**Issue by chris-sanders** [blakeblackshear/blakeshome-charts#42]
It looks like the [Restream](https://docs.frigate.video/configuration/restream) from go2rtc is exposed on port 8554 which isn't listed on the deployment or the service and there's no configuration for additional ports on either.

Can/should these be added or how is go2rtc and Restream intended to work?

**Comment by blakeblackshear** [comment]
I have decided to move off of k8s for my home server, so I don't have a good test environment to maintain this chart. I am happy to add others as contributors if someone else wants to step in.

**Comment by chris-sanders** [comment]
That's understandable. I might be interested I've got another chart I'm
working on right now and just got Frigate working this weekend (I didn't
have to expose this service just used the new card). I can't say I
understand how go2rtc is working w/o the service having the port mapped
through but I'll look at this chart next and see if I can help.

**Comment by aronymous** [comment]
I am willing to help maintain this chart. Please let me know.
